### ISSUE TITLE
Only first 12 seconds are being imported

### ISSUE THREAD

**Issue by TheRedstoneScientist** [nlaha/godot-midi#15]
After importing 
[Imagine dragons - Radioactive.zip](https://github.com/nlaha/godot-midi/files/14043848/Imagine.dragons.-.Radioactive.zip)
(made it a zip since git doesn't support mid)
I'm able to get it to print to the output but after about 12.1 seconds it always stops. In the inspector it only seems to have the first 12 seconds in the data there too.

**Comment by TheRedstoneScientist** [comment]
I'm unable to tell what happened but I had to reexport the midi

**Comment by nlaha** [comment]
Thanks for reporting this bug! I'll look into it. It is likely the midi file you are using has some uncommon midi events present that I haven't added support for. Until I can do further testing, I recommend you import and export the midi file from a well-known DAW like FL Studio to convert it to a standard midi format.

**Comment by nlaha** [comment]
Looking into the midi parsing code, and viewing the midi file you provided with a hex editor, it seems like there are some issues with the format. I'm able to import the first midi file you sent into FL Studio fine, but the second one actually seems corrupted past 27 seconds in, I suggest you find a difference source.

Regarding the first file however:
![image](https://github.com/nlaha/godot-midi/assets/10292944/2c516be0-c878-4309-8e2a-837a297d0317)

The midi file is storing the first control change event (event type 0xB0) as specified, but the events proceeding it don't have an event type field at all, and simply have the control subtype and value. I'm not sure how FL Studio gets around this inconsistency, but because I can't find any documentation regarding this anywhere online, I'm closing this issue for now. I have attached a version of your midi file re-exported through FL Studio that imports to Godot fine.
[Imagine dragons - Radioactive.zip](https://github.com/nlaha/godot-midi/files/14079472/Imagine.dragons.-.Radioactive.zip)
